version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: notedesk_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: notedesk_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
